name: Build and push recommendation-core image

on:
  push:
    branches:
      - main
    paths:
      - 'recommendation-core/**'

jobs:
  build-recommendation-core-image:
    name: Build and Push Recommendation Core Image
    runs-on: ubuntu-latest
    if: >
      (github.repository == 'rh-ai-kickstart/product-recommender-system') &&
      (github.event_name == 'push')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set version from run number
        id: version
        run: |
          echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push recommendation-core
        uses: docker/build-push-action@v5
        with:
          context: recommendation-core
          file: recommendation-core/Containerfile
          push: true
          tags: |
            quay.io/rh-ai-kickstart/recommendation-core:${{ steps.version.outputs.tag }}
            quay.io/rh-ai-kickstart/recommendation-core:latest
          build-args: |
            IMAGE_TAG=${{ steps.version.outputs.tag }}
